#ifndef LANCEDB_H
#define LANCEDB_H

#pragma once

/* Generated with cbindgen:0.26.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

#define NATIVE_SEGMENT_WIRE_VERSION 1

#define FFI_ERROR_NONE 0

#define FFI_ERROR_OPERATION 1

#define FFI_ERROR_PANIC 2

/**
 * Result type for C interface
 */
typedef struct SimpleResult {
  bool SUCCESS;
  char *ERROR_MESSAGE;
  int ERROR_CODE;
  char *RUNTIME_VERSION;
} SimpleResult;

/**
 * Version information
 */
typedef struct VersionInfo {
  int VERSION;
  int64_t TIMESTAMP;
  char *METADATA_JSON;
} VersionInfo;

/**
 * Connect to a LanceDB database (simple version)
 */
struct SimpleResult *simple_lancedb_connect(const char *uri, void **handle);

/**
 * Connect to a database with storage options
 */
struct SimpleResult *simple_lancedb_connect_with_options(const char *uri,
                                                         const char *options_json,
                                                         void **handle);

/**
 * Close a connection
 */
struct SimpleResult *simple_lancedb_close(void *handle);

/**
 * Delete rows from a table using SQL predicate (simple version)
 */
struct SimpleResult *simple_lancedb_table_delete(void *table_handle,
                                                 const char *predicate,
                                                 int64_t *deleted_count);

/**
 * Update rows in a table using SQL predicate and column updates (simple version)
 */
struct SimpleResult *simple_lancedb_table_update(void *table_handle,
                                                 const char *predicate,
                                                 const char *updates_json);

/**
 * Update rows using raw SQL expressions per column, with an optional
 * predicate. Unlike `simple_lancedb_table_update`, the per-column values
 * are passed through to lancedb's `UpdateBuilder.column(name, expr)`
 * verbatim — the caller is responsible for quoting string literals
 * (`'foo'`) and formatting vector literals (`[1.0, 2.0, ...]`). This
 * matches the Rust `Table::update()` builder's semantics one-for-one and
 * unlocks SQL expressions like `counter + 1` or `upper(name)` that the
 * JSON-literal path cannot represent.
 *
 * `predicate` may be NULL or empty to update every row (no WHERE).
 *
 * `assignments_json` schema:
 * ```json
 * [
 *   {"column": "i",    "expr": "i + 1"},
 *   {"column": "name", "expr": "'foo'"}
 * ]
 * ```
 * An array (not a map) preserves caller order and avoids `serde_json`
 * `Map` ordering surprises across versions.
 *
 * On success `result_json` is set to a CString containing
 * `{"rows_updated": <u64>, "version": <u64>}` which the caller must free
 * via `simple_lancedb_free_string`.
 */
struct SimpleResult *simple_lancedb_table_update_expr(void *table_handle,
                                                      const char *predicate,
                                                      const char *assignments_json,
                                                      char **result_json);

/**
 * Add JSON data to a table (simple version)
 * Converts JSON array of objects to Arrow RecordBatch and adds to table
 */
struct SimpleResult *simple_lancedb_table_add_json(void *table_handle,
                                                   const char *json_data,
                                                   int64_t *added_count);

/**
 * Add data to a table using Arrow IPC format (more efficient than JSON)
 * Accepts batch of records as Arrow IPC binary data
 */
struct SimpleResult *simple_lancedb_table_add_ipc(void *table_handle,
                                                  const uint8_t *ipc_data,
                                                  size_t ipc_len,
                                                  int64_t *added_count);

/**
 * Upsert data into a table using Arrow IPC format and a merge-insert config JSON.
 *
 * `config_json` schema:
 * ```json
 * {
 *   "on": ["col1", ...],
 *   "when_matched_update_all": bool,
 *   "when_matched_condition": null | "SQL string",
 *   "when_not_matched_insert_all": bool,
 *   "when_not_matched_by_source_delete": bool,
 *   "when_not_matched_by_source_filter": null | "SQL string",
 *   "timeout_ms": null | <u64>,
 *   "use_index": null | bool
 * }
 * ```
 */
struct SimpleResult *simple_lancedb_table_merge_insert_ipc(void *table_handle,
                                                           const char *config_json,
                                                           const uint8_t *ipc_data,
                                                           size_t ipc_len,
                                                           char **result_json);

/**
 * Get table names
 */
struct SimpleResult *simple_lancedb_table_names(void *handle, char ***names, int *count);

/**
 * Free table names array
 */
void simple_lancedb_free_table_names(char **names, int count);

/**
 * Initialize the simple LanceDB library
 */
int simple_lancedb_init(void);

/**
 * Free a SimpleResult
 */
void simple_lancedb_result_free(struct SimpleResult *result);

/**
 * Free a C string allocated by the library
 */
void simple_lancedb_free_string(char *s);

/**
 * Free a byte buffer allocated by the library.
 */
void simple_lancedb_free_bytes(uint8_t *data, size_t len);

/**
 * Create an index on the specified columns
 */
struct SimpleResult *simple_lancedb_table_create_index(void *table_handle,
                                                       const char *columns_json,
                                                       const char *index_type,
                                                       const char *index_name);

/**
 * Get all indexes for a table (returns JSON string)
 */
struct SimpleResult *simple_lancedb_table_get_indexes(void *table_handle, char **indexes_json);

/**
 * Retrieve statistics about an index
 */
struct SimpleResult *simple_lancedb_table_index_stats(void *table_handle,
                                                      const char *index_name,
                                                      char **index_stats_json);

/**
 * Drop the named index from the table. Returns SimpleResult::ok() when
 * the backend reports success, or SimpleResult::error() with a
 * backend-supplied message on a missing index / I/O failure / cancelled
 * runtime. The Go layer is responsible for swallowing the not-found
 * error when the caller asked for IF EXISTS semantics.
 */
struct SimpleResult *simple_lancedb_table_drop_index(void *table_handle, const char *index_name);

/**
 * Prewarm the named index by loading its on-disk pages into the index
 * cache. The call initiates prewarming and returns once the request is
 * accepted by the backend; pages are loaded up to the available cache
 * capacity. Not all index types support prewarming — unsupported types
 * surface as a backend error which is forwarded to the caller verbatim.
 *
 * Returns SimpleResult::ok() when prewarming was accepted, or
 * SimpleResult::error() with a backend-supplied message on a missing
 * index / unsupported type / I/O failure / cancelled runtime.
 */
struct SimpleResult *simple_lancedb_table_prewarm_index(void *table_handle, const char *index_name);

/**
 * Wait for the named indices to finish building, with a timeout in
 * milliseconds. An empty `index_names` array defaults to all indices on
 * the table. A `timeout_ms` value of 0 means "wait essentially forever"
 * (Duration::MAX). The call blocks the calling thread until either all
 * listed indices report no unindexed rows or the deadline elapses.
 *
 * Returns SimpleResult::ok() on success, or SimpleResult::error() with a
 * backend-supplied message on timeout / missing index / I/O failure.
 */
struct SimpleResult *simple_lancedb_table_wait_for_index(void *table_handle,
                                                         const char *const *index_names,
                                                         size_t index_names_count,
                                                         uint64_t timeout_ms);

/**
 * Create an index with full tuning parameters. The `config_json` is the
 * canonical surface for per-type tuning (num_partitions, m, ef_construction,
 * FTS options, etc.); the small top-level knobs (name/replace/
 * wait_timeout_ms) are passed as regular arguments so callers don't have to
 * encode them into JSON just to change a single bool.
 *
 * - `name` may be NULL for the backend default.
 * - `replace` matches lancedb's IndexBuilder::replace (default true in
 *   upstream; we forward the caller's choice verbatim).
 * - `wait_timeout_ms == 0` leaves the backend default (no wait).
 */
struct SimpleResult *simple_lancedb_table_create_index_v2(void *table_handle,
                                                          const char *columns_json,
                                                          const char *config_json,
                                                          const char *name,
                                                          bool replace,
                                                          uint64_t wait_timeout_ms);

/**
 * Count rows in a table (simple version)
 */
struct SimpleResult *simple_lancedb_table_count_rows(void *table_handle, int64_t *count);

/**
 * Get table version (simple version)
 */
struct SimpleResult *simple_lancedb_table_version(void *table_handle, int64_t *version);

/**
 * Get table schema as JSON (simple version)
 */
struct SimpleResult *simple_lancedb_table_schema(void *table_handle, char **schema_json);

/**
 * Get table schema as Arrow IPC binary format (more efficient than JSON)
 */
struct SimpleResult *simple_lancedb_table_schema_ipc(void *table_handle,
                                                     uint8_t **schema_ipc_data,
                                                     size_t *schema_ipc_len);

/**
 * Free IPC schema data allocated by simple_lancedb_table_schema_ipc
 */
void simple_lancedb_free_ipc_data(uint8_t *data);

/**
 * Enumerate fragments from exactly `dataset_version`.
 */
struct SimpleResult *simple_lancedb_table_list_fragments(void *table_handle,
                                                         uint64_t dataset_version,
                                                         uint8_t **output,
                                                         size_t *output_len);

/**
 * Train a shared IVF / IVF_PQ model on an exact dataset snapshot and fragment set.
 */
struct SimpleResult *simple_lancedb_table_prepare_index_model(void *table_handle,
                                                              const uint8_t *request,
                                                              size_t request_len,
                                                              uint8_t **output,
                                                              size_t *output_len);

/**
 * Build one fragment-scoped uncommitted vector index segment.
 */
struct SimpleResult *simple_lancedb_table_create_index_uncommitted(void *table_handle,
                                                                   const uint8_t *request,
                                                                   size_t request_len,
                                                                   uint8_t **output,
                                                                   size_t *output_len);

/**
 * Physically merge compatible uncommitted segments.
 */
struct SimpleResult *simple_lancedb_table_merge_existing_index_segments(void *table_handle,
                                                                        const uint8_t *request,
                                                                        size_t request_len,
                                                                        uint8_t **output,
                                                                        size_t *output_len);

/**
 * Atomically commit physical segments as one logical vector index.
 */
struct SimpleResult *simple_lancedb_table_commit_existing_index_segments(void *table_handle,
                                                                         const uint8_t *request,
                                                                         size_t request_len,
                                                                         uint8_t **output,
                                                                         size_t *output_len);

/**
 * Inspect committed physical segments for one logical index name.
 */
struct SimpleResult *simple_lancedb_table_inspect_index_segments(void *table_handle,
                                                                 const char *index_name,
                                                                 uint8_t **output,
                                                                 size_t *output_len);

/**
 * Execute a select query and return results as JSON.
 */
struct SimpleResult *simple_lancedb_table_select_query(void *table_handle,
                                                       const char *query_config_json,
                                                       char **result_json);

/**
 * Execute a select query and return results as Arrow IPC binary data.
 */
struct SimpleResult *simple_lancedb_table_select_query_ipc(void *table_handle,
                                                           const char *query_config_json,
                                                           uint8_t **result_ipc_data,
                                                           size_t *result_ipc_len);

/**
 * List every version reachable from the dataset. Returns a JSON array
 * of {version, timestamp, metadata} objects ordered as reported by the
 * backend. Caller owns versions_json and must free it with
 * simple_lancedb_free_string.
 */
struct SimpleResult *simple_lancedb_table_list_versions(void *table_handle, char **versions_json);

/**
 * Pin the table to a specific version. Subsequent reads see that
 * snapshot; writes are rejected until the table is brought back with
 * either checkout_latest or restore. Mirrors lancedb::Table::checkout.
 */
struct SimpleResult *simple_lancedb_table_checkout(void *table_handle, uint64_t version);

/**
 * Pin the table to the version referenced by the given tag.
 */
struct SimpleResult *simple_lancedb_table_checkout_tag(void *table_handle, const char *tag);

/**
 * Drop any prior checkout pin and resume tracking the latest manifest.
 */
struct SimpleResult *simple_lancedb_table_checkout_latest(void *table_handle);

/**
 * Promote the currently checked-out version to a new latest manifest.
 * Errors if the table is not in a checked-out state. Mirrors
 * lancedb::Table::restore exactly — the Python `restore(version)`
 * convenience overload is not available here; callers do
 * checkout(N) -> restore() in two steps.
 */
struct SimpleResult *simple_lancedb_table_restore(void *table_handle);

/**
 * List every tag on the table as a JSON object keyed by tag name.
 * Each value carries the pinned version, manifest_size, and an
 * optional branch (currently always absent for tags created via the
 * FFI). Caller owns tags_json and must free it with
 * simple_lancedb_free_string.
 */
struct SimpleResult *simple_lancedb_table_tags_list(void *table_handle, char **tags_json);

/**
 * Resolve a tag to its pinned version. Errors when the tag does not
 * exist. The version is written to *version_out on success.
 */
struct SimpleResult *simple_lancedb_table_tags_get_version(void *table_handle,
                                                           const char *tag,
                                                           uint64_t *version_out);

/**
 * Create a new tag pointing at the given version. Errors if the tag
 * already exists or the version is unknown.
 */
struct SimpleResult *simple_lancedb_table_tags_create(void *table_handle,
                                                      const char *tag,
                                                      uint64_t version);

/**
 * Delete a tag. Errors if the tag does not exist.
 */
struct SimpleResult *simple_lancedb_table_tags_delete(void *table_handle, const char *tag);

/**
 * Move an existing tag to a new version. Errors if the tag does not
 * exist or the version is unknown.
 */
struct SimpleResult *simple_lancedb_table_tags_update(void *table_handle,
                                                      const char *tag,
                                                      uint64_t version);

/**
 * Add new columns to the table by evaluating SQL expressions over
 * existing rows. `transforms_json` is a JSON array of
 * {"name": "<col>", "expression": "<sql>"} objects. Empty arrays are
 * rejected as a caller bug — adding zero columns is a no-op that
 * almost always indicates a missing argument.
 *
 * On success, the new commit version is written to *version_out. A
 * version of 0 indicates compatibility with legacy backends that do
 * not report a commit version (mirrors AddColumnsResult::version
 * semantics in lancedb).
 */
struct SimpleResult *simple_lancedb_table_add_columns(void *table_handle,
                                                      const char *transforms_json,
                                                      uint64_t *version_out);

/**
 * Alter existing columns — rename and/or change nullability.
 * `alterations_json` is a JSON array of {"path": "<col>", "rename":
 * "<new>", "nullable": <bool>} objects; rename and nullable are both
 * optional and "unset" means "leave that attribute alone". Empty
 * arrays are rejected.
 *
 * data_type casts are intentionally not exposed in v1 — they require
 * Arrow DataType serialization and are slated for a follow-up. Callers
 * who need a cast can drop and re-add the column through add_columns.
 *
 * On success, the new commit version is written to *version_out.
 */
struct SimpleResult *simple_lancedb_table_alter_columns(void *table_handle,
                                                        const char *alterations_json,
                                                        uint64_t *version_out);

/**
 * Drop columns from the table. `columns_json` is a JSON array of
 * strings naming the columns to remove. Empty arrays are rejected.
 *
 * On success, the new commit version is written to *version_out.
 */
struct SimpleResult *simple_lancedb_table_drop_columns(void *table_handle,
                                                       const char *columns_json,
                                                       uint64_t *version_out);

/**
 * Create a table with a simple JSON schema
 */
struct SimpleResult *simple_lancedb_create_table(void *handle,
                                                 const char *table_name,
                                                 const char *schema_json);

/**
 * Create a table with Arrow IPC schema (more efficient than JSON)
 */
struct SimpleResult *simple_lancedb_create_table_with_ipc(void *handle,
                                                          const char *table_name,
                                                          const uint8_t *schema_ipc,
                                                          size_t schema_len);

/**
 * Drop a table from the database (simple version)
 */
struct SimpleResult *simple_lancedb_drop_table(void *handle, const char *table_name);

/**
 * Open a table from the database (simple version)
 */
struct SimpleResult *simple_lancedb_open_table(void *handle,
                                               const char *table_name,
                                               void **table_handle);

/**
 * Close a table handle (simple version)
 */
struct SimpleResult *simple_lancedb_table_close(void *table_handle);

/**
 * Optimize the on-disk data and indices for better performance
 */
struct SimpleResult *simple_lancedb_table_optimize(void *table_handle, char **optimize_stats_json);

/**
 * Optimize the on-disk data and indices with a configurable
 * OptimizeAction. The `action_json` argument selects the sub-action and
 * carries its options; `OptimizeAction::All` (the original behaviour
 * available via `simple_lancedb_table_optimize`) corresponds to
 * `{"type":"all"}`.
 */
struct SimpleResult *simple_lancedb_table_optimize_v2(void *table_handle,
                                                      const char *action_json,
                                                      char **optimize_stats_json);

/**
 * Free a VersionInfo structure
 */
void lancedb_version_info_free(struct VersionInfo *version);

#endif /* LANCEDB_H */
